module CardsHelper
    def instructions
      if action_name  == "index" && controller_name == "cards"
         "Your workboard is modeled after a #{link_to "kanban board", "https://en.wikipedia.org/wiki/Kanban_board"} and is intended to let you and your commissioners track your work progress. The workboard has three modes. <br /><br />View mode shows you what other users see when they view your workboard. You can use it to check that it gets presented the way you want it to.<br /><br />Edit mode allows you to create new lists and items on those lists--and to modify and delete the ones you currently have. Each list has a customizable title, and each item has a customizable title and description, and can have an image attached to it. Note: A list or item is created in the database as soon as you click on the respective \u201CAdd\u201D button. The \u201CSave\u201D button on each card only needs to get pressed after you change the title, description, or image.<br /><br />Reorder mode allows you to move cards and lists around. You can change the order of the lists and of the cards within the lists. You can also move cards from one list onto another. You can save the updated ordering with the \u201CFinalize Order\u201D button in the lower left of the reorder section. Note: You can continue using all the other functions of the workboard <em class = 'danger'>except for saving an item with a new image attatched</em> without the unsaved order reverting; just make sure to finalize the order before you leave the workboard page entirely, refresh the page, or upload a new image attachment."
      end
      if action_name  == "index" && controller_name == "pools"
        "Click the add button in the lower right of your screen to make a new pool. The pool is now created in the database and appears at the end of the list. Enter the pool by clicking on its name in order to change its name and upload submissions to it. To destroy the pool, click the trash icon. To make it your main gallery, click the list-top icon." 
      end
      if action_name == "index" && controller_name == "order_forms" && (can_modify? @user)
         "Order forms are an easy way to get information from your commissioner about the work they want done. Each order form is a page you custom build to contain a series of questions you want to present to your commissioner--like giving them an application to fill out. For example, a character-sheet order form could ask for the sex, species, and colors of the commissioner's character, plus some personality details or backstory. After they are done and submit their order, the order will appear on your workboard for you to accept or deny, and the notification counter for new orders in the navigation bar will increase.<br /><br />You do not have to ask for contact information when you build your order form. When filling out your form, the commissioner will automatically be asked to enter their name and email so you know who placed the order with you. Alternately, they can sign into #{CONFIG[:name]} directly from the form or sign up if they don't already have an account; then their account name and email will appear on the order.<br /><br />Once you have built the form, you may click \u201CCopy link\u201D on the same row as the form on this page. (This is not the same link as appears in the address bar when you build the form.) Send this link to a commissioner, and they will be given the blank form to fill out. They can also share the same link with friends who might be interested in getting a commission from you; then their friends can order from you in the same way. The link never expires unless you delete the form from this page.<br /><br />Additionally, if you tell #{CONFIG[:name]} you are open for commissions and you have at least one order form, this will enable a link on both your profile page and your listing on the main page. When anyone clicks this link, they will be given the fillable version of your <b>default</b> order form. (You can turn this feature off in your settings.) Though this \u201CPlace Order\u201D link appears enabled to you as well if you have fulfilled the conditions--to remind you whether or not you are accepting orders--you will not be allowed to place orders with yourself.<br /><br />Start by clicking the add button floating in the lower right of your screen to make a new order form. The order form is now created in the database and appears at the end of the list. Click its name, and you will be taken to a page where you can set/change its name and build the form.  In the same way, you can also edit the contents of a form you've already built and saved. To destroy the form, click the trash icon. When destroying your default order form, the next form on the list automatically becomes the default."
      end
      if action_name == "show" && controller_name == "order_forms" && (can_modify? @user)
         "Click a button in the \u201CAdd\u201D area. The matching question template appears in the workspace box below. Fill in the \u201CQuestion\u201D field with the question you want your commissioner to answer.<br /><br />For the \u201Cshort response\u201D and \u201Cfree answer\u201D templates, the bordered \u201Cresponse area\u201D indicates you of the length of the text response your commissioner can give to your question. Within the \u201Cresponse area\u201D for the \u201Cchoose one\u201D and \u201Cchoose all that apply\u201D templates, you can add, remove, edit, and reorder choices for your commissioner to pick from in response to that question. For the two \u201Crequest references\u201D templates, the area below the question reminds you of the type of references you're asking for, links to outside sources or images uploaded directly to the order.<br /><br />To remove a question or choice, click on the <i class='material-icons'>#{CONFIG[:other_icons][:remove]}</i>.<br /><br />To reorder questions or choices, grab the <i class='material-icons'>#{CONFIG[:other_icons][:handle]}</i> and drag it to its new position.<br /><br />When you are done, click the save icon in the lower right of your screen. Your changes will be saved in the database. You can now grab the shareable link and send it to anyone, as described in the previous page's instructions. Whenever you edit your order form and save the changes, the fillable form at that link automatically updates. The link does not become invalid until you delete the form and always links to the newest version."
      end
    end

end